### ISSUE TITLE
Joint Type error

### ISSUE THREAD

**Issue by nag92** [ORB-HD/rbdl-orb#28]
When running the python example I am getting the following error. It seems to be a problem with 
The name of the joint. 

```
Traceback (most recent call last):
  File "/home/nathaniel/test.py", line 8, in <module>
    joint_rot_y = rbdl.Joint.fromJointType ("JointTypeRevoluteY")
  File "rbdl.pyx", line 1119, in rbdl.Joint.fromJointType
  File "rbdl.pyx", line 1089, in rbdl.Joint.__cinit__
KeyError: 'JointTypeRevoluteY'
[Finished in 0.2s with exit code 1]
[shell_cmd: python -u "/home/nathaniel/test.py"]
[dir: /home/nathaniel]
[path: /opt/ros/noetic/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/snap/bin]
```

**Comment by nag92** [comment]
closed with #29
